# Basic environment for Py-ART.
name: dissertation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - wradlib
  - cartopy
  - xarray
  - plotly
  - meshio
  - jupyterlab
  - numpy-stl
  - pip
  - pip:
     - arm_pyart
     - chart_studio
     - dash-obj-in-3dmesh
