# Basic environment for Py-ART.
name: dissertation
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - arm_pyart
  - act-atmos
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - wradlib
  - cartopy
  - xarray
  - plotly
  - meshio
  - jupyterlab
  - numpy-stl
  - pyvista
  - pip
  - pip:
     - chart_studio
     - dash-obj-in-3dmesh
