#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# define the surface features 
##runApplication surfaceFeatures
# create the background mesh
##runApplication blockMesh
#
# Run on single processer 
###runApplication snappyHexMesh -overwrite

# Generate patch infomration
###runApplication patchSummary
# Run the application 
##runApplication $(getApplication)

# generate the paraview file. 
##paraFoam -touch

##runApplication decomposePar -copyZero
##runParallel snappyHexMesh -overwrite

#runParallel patchSummary
runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime

#runApplication -s sample  postProcess -func sample

#------------------------------------------------------------------------------
